# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directories: 
      - "/sdk/identity"
    schedule:
      interval: "daily"
    reviewers: ["@jairmyree"]
    target-branch: "dependency-updates"
    commit-message:
      prefix: "[Identity] "
    groups:
      Identity-production_dependencies:
        dependency-type: "production"
      Identity-dev_dependencies:
        dependency-type: "development"
    ignore:
        - dependency-name: "*" 
          update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven" # See documentation for possible values
    directories: 
      - "/sdk/core"
    schedule:
      interval: "daily"
    reviewers: ["@jairmyree"]
    groups:
      Core-production_dependencies:
        dependency-type: "production"
      Core-dev_dependencies:
        dependency-type: "development"
    target-branch: "dependency-updates"
    ignore:
        - dependency-name: "*" 
          update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven" # See documentation for possible values
    directories: 
      - "/sdk/search"
    schedule:
      interval: "daily"
    reviewers: ["@jairmyree"]
    groups:
      Search-production_dependencies:
        dependency-type: "production"
    target-branch: "dependency-updates"
    ignore:
        - dependency-name: "*" 
          update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven" # See documentation for possible values
    directories: 
      - "/sdk/tables"
    schedule:
      interval: "daily"
    reviewers: ["@jairmyree"]
    groups:
      Tables-production_dependencies:
        dependency-type: "production"
    target-branch: "dependency-updates"
    ignore:
        - dependency-name: "*" 
          update-types: ["version-update:semver-major"]
          
