name: Dependabot Update External Dependencies
on: pull_request

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' 
    steps:
    - name: Fetch Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        alert-lookup: true
        compat-lookup: true
        skip-verification: true
        skip-commit-verification: true

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Adjust External Dependencies
      run: python eng/versioning/dependabot_update_external_dependencies.py --json '${{steps.dependabot-metadata.outputs.updated-dependencies-json}}'
    
        
      # The following properties are now available:
      #  - steps.metadata.outputs.dependency-names
      #  - steps.metadata.outputs.dependency-type
      #  - steps.metadata.outputs.update-type

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update External Dependencies"
        git push origin HEAD:${{ github.event.pull_request.head.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-Approve and Merge Pull Request
      run: |
        gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          PR_URL="${{ github.event.pull_request.html_url }}"
          UPDATE_TYPE="${{ steps.dependabot-metadata.outputs.update-type }}"
          COMPATIBILITY_SCORE="${{ steps.dependabot-metadata.outputs.compatibility-score }}"

          if "$UPDATE_TYPE" == "version-update:semver-patch" || ["$UPDATE_TYPE" == "version-update:semver-minor" && $COMPATIBILITY_SCORE >= 80]; then
            gh pr review --approve "$PR_URL"
            gh pr merge "$PR_URL" --auto --squash --admin
          else
            echo "PR does not meet criteria for auto-merge."
          fi


